# Generated by Django 5.0.2 on 2024-06-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctorinfo_delete_doctorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthPlan',
        ),
    ]
