# Generated by Django 5.0.2 on 2024-06-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_healthfact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfact',
            name='image',
        ),
        migrations.AddField(
            model_name='healthfact',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
